# -*- coding: utf-8 -*-
"""deeppavlov_qa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e3HCzG7RZxuJZdoFzv395M7zGO0g9eNO
"""

from deeppavlov import build_model, configs
model = build_model(configs.squad.squad, download=True)
content = """The total number of coronavirus cases in India has reached 101,261, according to Worldometer.\
 As many as 3,163 people have died from the disease in the country, while a little over 39,000 have recovered. \
 The count of cases rose even as several states announced easing of restrictions for the extended lockdown\
  in force till May 31. Several states have ordered reopening of markets, local transport and even salons\
  in areas that are considered safe from coronavirus. However, schools, colleges, theatres and malls are among\
  those that would remain closed"""
question = "which institutes will be closed"
print(model([content], [question])[0][0].capitalize())